version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Environment: $APP_ENV"
      - echo "Version: $APP_VERSION"

  build:
    commands:
      - echo "Running build..."
      - npm run build || echo "No build script found"

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
